### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by haarchri** [kyverno/policies#461] opened 2022-11-28 13:52 UTC
### Kyverno Version

1.7.x

### Kubernetes Version

1.22.x

### Kubernetes Platform

EKS

### Description

we created the following policy:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Tenant
    policies.kyverno.io/description: Sync docker.io pull-secret to tenant-namespaces
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/title: Sync Image Pull Secret docker.io
  name: sync-docker-io-secret
spec:
  background: true
  failurePolicy: Fail
  generateExistingOnPolicyUpdate: true
  rules:
  - generate:
      apiVersion: v1
      clone:
        name: docker.io
        namespace: flux-system
      kind: Secret
      name: docker-io-image-pull-secret
      namespace: '{{request.object.metadata.name}}'
      synchronize: true
    match:
      resources:
        kinds:
        - Namespace
    name: sync-docker-io-secret
  validationFailureAction: audit
```

any reason why the secrets not synced to kube-system namespace? in all other namespaces the sync is working

### Steps to reproduce

create the policy
no secret in kube-system namespace

### Expected behavior

secret also created in kube-system namespace

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment] 2022-11-28 14:16
This isn't a bug with the policy. Kyverno by default excludes certain "core" Namespaces such as `kube-system` and the Kyverno Namespace via the [resource filter](https://kyverno.io/docs/installation/#resource-filters). Because these are excluded, there is no AdmissionReview request that Kyverno acknowledges from them, which means the `namespace: '{{request.object.metadata.name}}'` line will be empty.

Closing as this is not a bug but feel free to reply.

**Closed by chipzoller** 2022-11-28 14:16 UTC
Labels: bug

**Comment by haarchri** [comment] 2022-11-28 14:34
any option to sync imagepullsecrets to kube-system instead ?

**Comment by chipzoller** [comment] 2022-11-29 12:23
You should just be able to remove the `namespace` field. Kyverno will add it as needed.
