### ISSUE TITLE
Verify Flux Sources

### ISSUE THREAD

**Issue by zensqlmonitor** [kyverno/policies#401] opened 2022-09-24 16:17 UTC
Kyverno Version
1.7.x

Kubernetes Version
1.23.x

Kubernetes Platform
EKS

Description

When trying to do a Kustomization reconciliation with Flux, resources of kinds ImageRepository is not accepted (works for HelmRepository and GitRepository)

E0924 16:06:30.959019       1 admission.go:95] WebhookServer/PolicyValidationWebhook "msg"="policy validation errors" "error"="the kind defined in the any match resource is invalid: unable to convert GVK to GVR for kinds [ImageRepository], err: kind 'ImageRepository' not found in apiVersion ''" "gvk"="kyverno.io/v1, Kind=ClusterPolicy" "kind"={"group":"kyverno.io","version":"v

Policy:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-repositories
  annotations:
    policies.kyverno.io/title: Verify Flux Sources
    policies.kyverno.io/category: Flux
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.7.3, 1.8.0-rc2
    policies.kyverno.io/minversion: 1.7.3
    kyverno.io/kubernetes-version: "1.23-1.24"
    policies.kyverno.io/subject: ImageRepository
    policies.kyverno.io/description: >-
      Flux source APIs include a number of different sources such as
      GitRepository, Bucket, HelmRepository, and ImageRepository resources. Each of these
      by default can be pointed to any location. In a production environment,
      it may be desired to restrict these to only known sources to prevent
      accessing outside sources. This policy verifies that each of the Flux
      sources comes from a trusted location.
spec:  
  validationFailureAction: audit # Change to 'enforce' once the specific org url is set.
  rules:
    - name: MyOrg-image-repositories-only
      match:
        any:
        - resources:
            kinds:
              - ImageRepository
      exclude:
        any:
        - resources:
            namespaces:
              - flux-system
              - kube-system
      validate:
        message: ".spec.image must be from an image repository in the org X"
        pattern:
          spec:
            image: "XXX?*" 
```

**Comment by chipzoller** [comment] 2022-09-24 16:34
Interesting. What versions of Kyverno and Flux? Do you get the same error if you remove the exclude statement?

**Comment by zensqlmonitor** [comment] 2022-09-24 17:25
Kyverno version: 1.7.3
flux: v0.34.0
helm-controller: v0.24.0
kustomize-controller: v0.28.0
notification-controller: v0.26.0
source-controller: v0.29.0
-------------------------------------
Same error when exlude statement is removed:
kyverno-policies     84m   False     ClusterPolicy/verify-image-repositories dry-run failed, error: admission webhook "validate-policy.kyverno.svc" denied the request: the kind defined in theany match resource is invalid: unable to convert GVK to GVR for kinds [ImageRepository], err: kind 'ImageRepository' not found in apiVersion ''...

**Comment by zensqlmonitor** [comment] 2022-10-04 09:29
Hello,

were you able to reproduce this error ?
Thanks.

**Comment by chipzoller** [comment] 2022-10-04 12:21
Yes, you're getting this error because you have not installed Flux with the `image-reflector-controller` extra. Without this flag/configuration, Flux will not create the ImageRepositories CRD. If Flux does not create this CRD, Kyverno cannot find it when you create the policy.

Closing, not a bug.

**Closed by chipzoller** 2022-10-04 12:21 UTC

**Comment by zensqlmonitor** [comment] 2022-10-04 14:36
Thanks for the feedback. 
Indeed, Flux was installed with eksctl and the default configuration.
